// INSA Static Content Data
// All content sourced from insa.gov.et — no invented information

export const INSA_INFO = {
    name: 'Information Network Security Administration',
    acronym: 'INSA',
    tagline: 'Securing Ethiopia\'s Digital Future',
    mission: 'To establish a national capacity that ensures the security of information and information infrastructure, and enables information superiority, thereby safeguarding national interests.',
    vision: 'To become a pioneering institution in Africa that ensures information superiority and digital sovereignty.',
    values: ['Integrity', 'Excellence', 'Trust-Worthiness', 'Synergy', 'Patriotism'],
    mandate: 'Established under Council of Ministers Regulation No. 130/2007, INSA is Ethiopia\'s lead institution for cybersecurity policy, infrastructure protection, and digital sovereignty.',
    contact: {
        phone: '(+251) 113-71-71-14',
        phoneAlt: '(+251) 113717114',
        email: 'contact@insa.gov.et',
        address: 'Welo Sefer China Street, Addis Ababa, Ethiopia',
        hours: 'Monday – Friday: 8:30 AM – 5:30 PM',
    },
    social: {
        youtube: 'https://www.youtube.com/channel/UCTc5kO3p6xAQSObDdx_Eg3w',
        linkedin: 'https://www.linkedin.com/company/information-network-security-agency/',
        twitter: 'https://x.com/INSAEthio',
        facebook: 'https://web.facebook.com/INSA.ETHIOPIA',
        telegram: 'https://t.me/insagovet',
    },
    reportUrl: 'https://www.ethiocert.gov.et/incident-report',
    grcUrl: 'https://grcservices.insa.gov.et/',
    subconUrl: 'https://recruitment.insa.gov.et/Pages/RegisterOrganization.aspx',
    copyright: '© 2025 Information Network Security Administration. All rights reserved.',
}

export const SERVICES = [
    {
        slug: 'digital-forensics',
        number: '01',
        title: 'Digital Forensic Service',
        category: 'Investigation',
        shortDesc: 'Investigation and recovery of data, information, and digital activity evidence to support legal and security proceedings.',
        fullDesc: 'INSA\'s Digital Forensic Service provides comprehensive investigation and recovery of digital data, information, and activity trails. Supporting national law enforcement and institutional security, the service delivers rigorous evidence handling for legal and regulatory proceedings.',
        icon: 'Search',
    },
    {
        slug: 'ethiocert',
        number: '02',
        title: 'Ethio Cyber Emergency Response Team',
        category: 'Incident Response',
        shortDesc: '24/7 national cyber incident monitoring, threat coordination, and rapid emergency response for critical systems.',
        fullDesc: 'The Ethio-CERT operates as Ethiopia\'s national Computer Emergency Response Team, providing round-the-clock monitoring of the national cyberspace, coordinating responses to major cyber incidents affecting government and critical infrastructure.',
        icon: 'Shield',
    },
    {
        slug: 'cloud-seeding',
        number: '03',
        title: 'Cloud Seeding',
        category: 'Technology Services',
        shortDesc: 'Weather modification and atmospheric technology initiative supporting Ethiopia\'s agricultural and water security goals.',
        fullDesc: 'INSA\'s Cloud Seeding program applies advanced atmospheric technology to support Ethiopia\'s agricultural resilience and water security objectives through controlled weather modification activities.',
        icon: 'Cloud',
    },
    {
        slug: 'fraud-prevention',
        number: '04',
        title: 'Fraud Prevention Service',
        category: 'Cyber Crime',
        shortDesc: 'Prevention and control of cyber-enabled financial crimes, identity fraud, and digital asset theft targeting citizens and institutions.',
        fullDesc: 'The Fraud Prevention Service works to detect, analyze, and prevent cyber-enabled financial crimes, identity fraud, and digital asset theft. The service supports both government institutions and the public in safeguarding against evolving cybercriminal threats.',
        icon: 'Lock',
    },
    {
        slug: 'cyber-audit',
        number: '05',
        title: 'Cybersecurity Audit & Evaluation',
        category: 'Assessment',
        shortDesc: 'Institutional security assessment, penetration testing, and compliance evaluation for government and critical infrastructure entities.',
        fullDesc: 'INSA conducts rigorous cybersecurity audits and evaluations for government institutions and critical infrastructure operators. Services include vulnerability assessments, penetration testing, security gap analysis, and compliance verification against national standards.',
        icon: 'ClipboardCheck',
    },
    {
        slug: 'counter-intelligence',
        number: '06',
        title: 'Counter Intelligence Service',
        category: 'National Security',
        shortDesc: 'Safeguarding Ethiopia\'s strategic national assets and confidential information against espionage and state-sponsored threats.',
        fullDesc: 'The Counter Intelligence Service protects Ethiopia\'s critical strategic assets, sensitive government information, and national interests against foreign espionage, insider threats, and state-sponsored cyber operations.',
        icon: 'EyeOff',
    },
]

export const PRODUCTS = [
    {
        slug: 'gasha-vpn',
        name: 'Gasha VPN',
        category: 'Network Security',
        shortDesc: 'Secure network encryption protecting data against eavesdropping and interception for government and enterprise.',
        featured: true,
        icon: 'Network',
        color: 'blue',
    },
    {
        slug: 'derash',
        name: 'Derash',
        category: 'Digital Finance',
        shortDesc: 'Sovereign digital bill aggregator platform for secure digital payment and billing infrastructure.',
        featured: false,
        icon: 'CreditCard',
        color: 'cyan',
    },
    {
        slug: 'gasha-antivirus',
        name: 'Gasha Antivirus',
        category: 'Endpoint Security',
        shortDesc: 'Locally engineered cybersecurity software for malware detection, removal, and endpoint protection.',
        featured: true,
        icon: 'Shield',
        color: 'blue',
    },
    {
        slug: 'gasha-waf',
        name: 'Gasha WAF',
        category: 'Web Security',
        shortDesc: 'Next-generation Web Application Firewall providing proactive cyber threat mitigation for digital services.',
        featured: false,
        icon: 'Layers',
        color: 'cyan',
    },
    {
        slug: 'sirkuni',
        name: 'Sirkuni',
        category: 'Secure Communications',
        shortDesc: 'Secure internal government messaging application replacing commercial platforms with sovereign communications.',
        featured: true,
        icon: 'MessageSquare',
        image: '/assets/uploads/products/sirkuni.png',
        color: 'blue',
    },
    {
        slug: 'erga',
        name: 'Erga (Ergamail)',
        category: 'Enterprise Email',
        shortDesc: 'Enterprise email system tailored for public sector digital autonomy and secure official communications.',
        featured: false,
        icon: 'Mail',
        color: 'cyan',
    },
    {
        slug: 'debo',
        name: 'Debo',
        category: 'Cloud Infrastructure',
        shortDesc: 'Indigenous cloud and sovereign infrastructure hosting platform for government digital services.',
        featured: false,
        icon: 'Server',
        image: '/assets/uploads/products/debo.png',
        color: 'cyan',
    },
    {
        slug: 'enyuma-iam',
        name: 'Enyuma IAM',
        category: 'Identity & Access',
        shortDesc: 'Enterprise Identity and Access Management platform for secure digital identity governance.',
        featured: false,
        icon: 'Users',
        image: '/assets/uploads/products/enyuma.png',
        color: 'blue',
    },
]

export const NEWS = [
    {
        slug: 'critical-infrastructure-proclamation-consultative-forum',
        title: 'INSA Hosts Consultative Forum on Critical Infrastructure Cybersecurity Proclamation and Designation Standard',
        category: 'Policy & Legislation',
        date: '2026-08-15',
        excerpt: 'INSA convened a high-level consultative forum bringing together key stakeholders to deliberate on the newly enacted Critical Infrastructure Cybersecurity Proclamation No. 1426/2026 and the accompanying designation standards.',
        featured: true,
        image: null,
    },
    {
        slug: 'addis-ababa-police-delegation',
        title: 'INSA Hosts Senior Addis Ababa Police Leadership Delegation',
        category: 'Partnerships',
        date: '2026-07-22',
        excerpt: 'Senior leadership from the Addis Ababa Police Commission visited INSA headquarters for capacity-building discussions and strategic cooperation on cybercrime investigation and digital forensics.',
        featured: false,
        image: null,
    },
    {
        slug: '5th-cyber-talent-summer-camp',
        title: '5th Cyber Talent Summer Camp Officially Launched',
        category: 'Capacity Building',
        date: '2026-06-10',
        excerpt: 'INSA officially launched the 5th Cyber Talent Summer Camp, an annual initiative aimed at identifying and nurturing the next generation of Ethiopian cybersecurity professionals.',
        featured: false,
        image: null,
    },
    {
        slug: 'critical-infrastructure-proclamation-digital-sovereignty',
        title: 'Critical Infrastructure Cybersecurity Proclamation Marks a Major Step Toward Safeguarding Ethiopia\'s Digital Sovereignty',
        category: 'Policy & Legislation',
        date: '2026-05-30',
        excerpt: 'INSA Director General Tigist Hamid addressed the landmark Critical Infrastructure Cybersecurity Proclamation, calling it a foundational milestone in Ethiopia\'s journey toward comprehensive digital sovereignty.',
        featured: false,
        image: null,
    },
]

export const DOCUMENTS = [
    {
        id: 'national-cyber-awareness-2024',
        title: 'National Cybersecurity Awareness Level Assessment 2024',
        category: 'Research & Reports',
        year: 2024,
        type: 'PDF',
        description: 'Annual assessment of national cybersecurity awareness levels across government, private sector, and civil society.',
    },
    {
        id: 'critical-infra-proclamation-1426',
        title: 'Critical Infrastructure Cybersecurity Proclamation No. 1426/2026',
        category: 'Legislation',
        year: 2026,
        type: 'PDF',
        description: 'Official proclamation establishing legal framework for critical infrastructure cybersecurity requirements and designations.',
    },
    {
        id: 'prohibited-technology-list',
        title: 'Prohibited Technology Product Lists',
        category: 'Regulatory',
        year: 2025,
        type: 'PDF',
        description: 'Official list of technology products prohibited from import, export, or deployment within Ethiopia.',
    },
    {
        id: 'restricted-technology-list',
        title: 'Restricted Technology Product Lists',
        category: 'Regulatory',
        year: 2025,
        type: 'PDF',
        description: 'Official list of technology products requiring special security clearance and regulatory approval.',
    },
    {
        id: 'it-security-clearance-1310',
        title: 'Information Technology Products Security Clearance and Control Proclamation 1310/2023',
        category: 'Legislation',
        year: 2023,
        type: 'PDF',
        description: 'Proclamation governing security clearance requirements for IT products used in government and critical infrastructure.',
    },
    {
        id: 'secure-website-management-standard',
        title: 'Secure Website Management Standard',
        category: 'Standards',
        year: 2024,
        type: 'PDF',
        description: 'National technical standard for secure design, deployment, and management of government and institutional websites.',
    },
    {
        id: 'cyber-risk-assessment-framework',
        title: 'Cyber Security Risk Assessment Framework',
        category: 'Frameworks',
        year: 2024,
        type: 'PDF',
        description: 'National framework providing methodology and guidelines for conducting cybersecurity risk assessments.',
    },
    {
        id: 'national-cyber-framework-methodology',
        title: 'National Cyber Security Framework Development Methodology',
        category: 'Frameworks',
        year: 2023,
        type: 'PDF',
        description: 'Methodology document describing the systematic approach used to develop the national cybersecurity framework.',
    },
    {
        id: 'cyber-audit-evaluation',
        title: 'Cyber Security Audit and Evaluation',
        category: 'Standards',
        year: 2024,
        type: 'PDF',
        description: 'Standard defining requirements and procedures for cybersecurity audit and evaluation processes.',
    },
    {
        id: 'critical-mass-cyber-requirement',
        title: 'Critical Mass Cyber Security Requirement Standard',
        category: 'Standards',
        year: 2024,
        type: 'PDF',
        description: 'Minimum cybersecurity requirement standards applicable to critical mass information systems and infrastructure.',
    },
]

export const AWARENESS_TIPS = [
    {
        number: '01',
        title: 'Use Strong Passwords',
        desc: 'Create unique, complex passwords for every account. Use a combination of letters, numbers, and special characters. Never reuse passwords across services.',
    },
    {
        number: '02',
        title: 'Enable Two-Factor Authentication',
        desc: 'Add an extra layer of security to all accounts by enabling 2FA. Even if your password is compromised, 2FA prevents unauthorized access.',
    },
    {
        number: '03',
        title: 'Keep Software Updated',
        desc: 'Regularly update operating systems, applications, and security software. Updates patch known vulnerabilities that attackers actively exploit.',
    },
    {
        number: '04',
        title: 'Be Cautious with Emails',
        desc: 'Do not click links or open attachments from unknown senders. Verify the sender\'s identity before sharing sensitive information via email.',
    },
    {
        number: '05',
        title: 'Guard Against Social Engineering',
        desc: 'Be skeptical of unsolicited calls, messages, or emails requesting personal information or urgency. Verify requests through official channels.',
    },
    {
        number: '06',
        title: 'Secure Your Network',
        desc: 'Use secure Wi-Fi networks and avoid public Wi-Fi for sensitive transactions. Enable network encryption and use VPN services for added protection.',
    },
]

export const NAV_ITEMS = [
    { label: 'Home', href: '/' },
    { label: 'About', href: '/about' },
    { label: 'Services', href: '/services' },
    { label: 'Products', href: '/products' },
    { label: 'News', href: '/news' },
    { label: 'Documents', href: '/documents' },
    {
        label: 'INSA Request',
        href: '#',
        children: [
            { label: 'Request Cyber Audit', href: '/request/cyber-audit' },
            { label: 'Request Secure Systems', href: '/request/secure-systems' },
            { label: 'Register as SubCon', href: 'https://recruitment.insa.gov.et/Pages/RegisterOrganization.aspx', external: true },
            { label: 'Governance Risk & Compliance', href: 'https://grcservices.insa.gov.et/', external: true },
        ],
    },
]

export const FOOTER_LINKS = {
    about: [
        { label: 'About INSA', href: '/about' },
        { label: 'Mission & Vision', href: '/about#mission' },
        { label: 'Leadership', href: '/about#leadership' },
        { label: 'Contact', href: '/contact' },
    ],
    services: [
        { label: 'Digital Forensics', href: '/services/digital-forensics' },
        { label: 'Ethio-CERT', href: '/services/ethiocert' },
        { label: 'Fraud Prevention', href: '/services/fraud-prevention' },
        { label: 'Cyber Audit', href: '/services/cyber-audit' },
        { label: 'Counter Intelligence', href: '/services/counter-intelligence' },
    ],
    products: [
        { label: 'Gasha VPN', href: '/products/gasha-vpn' },
        { label: 'Gasha Antivirus', href: '/products/gasha-antivirus' },
        { label: 'Gasha WAF', href: '/products/gasha-waf' },
        { label: 'Sirkuni', href: '/products/sirkuni' },
        { label: 'Erga (Ergamail)', href: '/products/erga' },
        { label: 'Debo', href: '/products/debo' },
        { label: 'Enyuma IAM', href: '/products/enyuma-iam' },
    ],
    resources: [
        { label: 'Documents', href: '/documents' },
        { label: 'Standards & Frameworks', href: '/documents#standards' },
        { label: 'Legislation', href: '/documents#legislation' },
        { label: 'INSA Request', href: '/request' },
    ],
}
